### ISSUE TITLE
AttributeError: 'America/Toronto' object has no attribute 'upper'

### ISSUE THREAD

**Issue by DaniyalDhz** [stub42/pytz#52]
Hi there,

I'm trying to get the local timezone:

```
from tzlocal import get_localzone
local_tz = get_localzone() 
tz = pytz.timezone(zone=get_localzone())

today = datetime.now(tz=tz)
start = today.replace(hour=0, minute=0, second=0, microsecond=0)
end = start + timedelta(1)
print(start, end)
```
But I get:
```
Traceback (most recent call last):
  File "/Users/Daniyal/Desktop/Test/Test.py", line 18, in <module>
    tz = pytz.timezone(zone=get_localzone())
  File "/Users/Daniyal/opt/anaconda3/lib/python3.8/site-packages/pytz/__init__.py", line 163, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'America/Toronto' object has no attribute 'upper'
```

**Comment by zeviel** [comment]
any solution?
